name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: nightly
          components: rustfmt

      - name: rustfmt
        run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - uses: taiki-e/install-action@e49978b799e49ff429d162b7a30601a569ab6538 # v2.81.1
        with:
          tool: cargo-hack

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          # only save the cache on the main branch
          # cf https://github.com/Swatinem/rust-cache/issues/95
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Clippy
        run: cargo hack --each-feature clippy --all-targets -- -D warnings

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          # only save the cache on the main branch
          # cf https://github.com/Swatinem/rust-cache/issues/95
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Start test dependencies
        run: docker compose -f "./testing-docker-compose.yml" up -d

      - name: Run tests
        env:
          AWS_DEFAULT_REGION: localhost
          AWS_ACCESS_KEY_ID: x
          AWS_SECRET_ACCESS_KEY: x
        run: cargo test --all-features

      - name: Stop test dependencies
        if: success() || failure()
        # use compose kill instead of stop because we don't care about clean
        # shutdown in the ephemeral CI environment
        run: docker compose -f "./testing-docker-compose.yml" kill

  prek:
    name: Validate prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
        with:
          # the check that we're not committing to main obviously is only useful locally
          extra-args: "--all-files --skip no-commit-to-branch"
