name: Rust Lib Security

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
      - '.github/workflows/rust-security.yml'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '.github/workflows/rust-security.yml'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
